name: postgresql
version: 0.3.1+1
author: Greg Lowe <greg@vis.net.nz>
description: Postgresql database driver.
homepage: https://github.com/xxgreg/dart_postgresql
environment:
  sdk: ">=0.8.10+6 <2.0.0"
dependencies:
  crypto: ">=0.9.0 <0.10.0"
dev_dependencies:
  test: ">=0.12.0 <0.13.0"
  yaml: ">=0.9.0 <3.0.0"
